//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtmSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Id { get; set; }
        public int CardId { get; set; }
        public Nullable<decimal> OldAmount { get; set; }
        public decimal NewAmount { get; set; }
    
        public virtual CardAccount CardAccount { get; set; }
    }
}
